### ISSUE TITLE
Feature request: add support for pins

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/connectapi#50] opened 2020-03-05 12:48 UTC
Hi,

Pins are incredibly useful, https://github.com/rstudio/pins, and it would be awesome if one could track their use with the connectapi in a similar manner that one does for Shiny/Static content.

Additionally, it would be very useful to know what shiny apps/static content make use of a pin

Thanks

Iain

**Comment by slopp** [comment] 2020-03-05 17:42
Pins are treated as static content, so their usage information is available both in Connect (the info pane for a pin will show a viewership sparkling) as well as more granular access data through the Connect usage API. 

Was there a particular doc that mis-spoke here and gave the impression the usage data was not available? I'd be happy to clarify that!

**Comment by tbradley1013** [comment] 2020-03-05 17:47
The confusion is likely my fault. @iainmwallace  filed an issue on the [`connectAnalytics`](https://github.com/tbradley1013/connectAnalytics) package asking for the addition of pins in the usage data. I don't utilize pins at the moment on my system, which is what I develop against and hadn't seen pins discussed in the API docs so I told him to file a request here for their addition. 

@iainmwallace  if pins are included in the static content output, then they should be displayed on the `connectAnalytics`  dashboard with the other static content.

**Comment by tbradley1013** [comment] 2020-03-05 20:23
Looking into it more closely, the reason it wasn't showing up on the `connectAnalytics` dashboard is because when a pin is deployed to the rsconnect system it does not have a title associated with it when you query the content information (i.e. via `get_content`). 

I am not sure whether that is intentional or, if not, whether that is an Connect issue or a `pins` issue.  It looks like a title does appear if is updated through the Connect interface (and I assume through the API), so I am guessing it is a `pins` issue.

**Comment by colearendt** [comment] 2020-03-05 21:25
Confirmed on our server - pins do not have titles by default. So we could definitely could add that as a feature request in `pins`. The other alternative is to `coalesce(title, name)` in any presentation of title 😄

**Comment by colearendt** [comment] 2020-05-04 02:07
Glad to hear this is functioning! I'm going to close this since `pins` usage data is available but can be easily missed due to the missing titles. If you would like for `pins` to have titles, that probably fits as a feature request on https://github.com/rstudio/pins

**Closed by colearendt** 2020-05-04 02:07 UTC
